#include "adif_log.hpp"

#include <algorithm>
#include <cerrno>
#include <cctype>
#include <cstdio>
#include <ctime>
#include <string_view>
#include <sys/stat.h>
#include <unistd.h>
#include <utility>

#include "esp_log.h"

namespace ham::logger {
namespace {

constexpr char TAG[] = "adif_log";
constexpr std::string_view HEADER =
    "Generated by HAM CW Logger Cardputer\r\n"
    "<ADIF_VER:5>3.1.4<PROGRAMID:23>HAM_CW_LOGGER_CARDPUTER"
    "<PROGRAMVERSION:5>0.1.0<EOH>\r\n";

void append_field(std::string &output, std::string_view name, std::string_view value) {
  if (value.empty()) return;
  output.push_back('<');
  output.append(name);
  output.push_back(':');
  output.append(std::to_string(value.size()));
  output.push_back('>');
  output.append(value);
}

bool sync_and_close(FILE *file, bool written) {
  bool ok = written;
  if (std::fflush(file) != 0) ok = false;
  if (fsync(fileno(file)) != 0) ok = false;
  if (std::fclose(file) != 0) ok = false;
  return ok;
}

} // namespace

bool AdifLog::initialize(std::string file_path) {
  ready_.store(false);
  file_path_ = std::move(file_path);
  if (file_path_.empty() || !write_header_if_needed()) return false;

  FILE *file = std::fopen(file_path_.c_str(), "ab");
  if (!file) {
    ESP_LOGE(TAG, "Could not open %s for append: errno=%d", file_path_.c_str(), errno);
    return false;
  }
  const bool ok = sync_and_close(file, true);
  ready_.store(ok);
  if (ok) ESP_LOGI(TAG, "ADIF log ready: %s", file_path_.c_str());
  return ok;
}

bool AdifLog::write_header_if_needed() {
  struct stat information {};
  const int stat_result = stat(file_path_.c_str(), &information);
  if (stat_result == 0 && information.st_size > 0) return true;
  if (stat_result != 0 && errno != ENOENT) {
    ESP_LOGE(TAG, "Could not inspect %s: errno=%d", file_path_.c_str(), errno);
    return false;
  }

  FILE *file = std::fopen(file_path_.c_str(), "wb");
  if (!file) {
    ESP_LOGE(TAG, "Could not create %s: errno=%d", file_path_.c_str(), errno);
    return false;
  }
  const bool written = std::fwrite(HEADER.data(), 1, HEADER.size(), file) == HEADER.size();
  const bool ok = sync_and_close(file, written);
  if (!ok) ESP_LOGE(TAG, "Could not write ADIF header to %s", file_path_.c_str());
  return ok;
}

bool AdifLog::append(const QsoRecord &record) {
  if (!ready_.load()) return false;

  std::tm utc{};
  if (!gmtime_r(&record.timestamp_utc, &utc)) return false;
  char date[9]{};
  char time[7]{};
  if (std::strftime(date, sizeof(date), "%Y%m%d", &utc) == 0 ||
      std::strftime(time, sizeof(time), "%H%M%S", &utc) == 0) {
    return false;
  }

  std::string band = record.band;
  std::transform(band.begin(), band.end(), band.begin(),
                 [](unsigned char value) { return static_cast<char>(std::toupper(value)); });

  std::string line;
  line.reserve(256);
  append_field(line, "CALL", record.callsign);
  append_field(line, "QSO_DATE", date);
  append_field(line, "TIME_ON", time);
  append_field(line, "BAND", band);
  append_field(line, "FREQ", record.frequency_mhz);
  append_field(line, "MODE", "CW");
  append_field(line, "RST_SENT", record.rst_sent);
  append_field(line, "RST_RCVD", record.rst_received);
  if (!record.pota_reference.empty()) {
    append_field(line, "MY_SIG", "POTA");
    append_field(line, "MY_SIG_INFO", record.pota_reference);
  }
  line.append("<EOR>\r\n");

  FILE *file = std::fopen(file_path_.c_str(), "ab");
  if (!file) {
    ready_.store(false);
    ESP_LOGE(TAG, "Could not reopen ADIF log: errno=%d", errno);
    return false;
  }
  const bool written = std::fwrite(line.data(), 1, line.size(), file) == line.size();
  const bool ok = sync_and_close(file, written);
  if (!ok) {
    ready_.store(false);
    ESP_LOGE(TAG, "ADIF record write failed for %s", record.callsign.c_str());
    return false;
  }

  ESP_LOGI(TAG, "QSO appended: %s %s %sZ", record.callsign.c_str(), date, time);
  return true;
}

} // namespace ham::logger
